name: Deploy gh-pages generate_204 No Content

on:
  push:
    branches:
      - main  # Ganti 'main' jika branch utama Anda berbeda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create /generate_204 response
      run: |
        mkdir -p public
        echo "" > public/generate_204
        echo "" > public/index.html

    - uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
